<!DOCTYPE html>
<!-- Header //-->
<html>

<head>

    <title>
        <?=$title; ?> : Pop PHP Framework Skeleton Application
    </title>

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="initial-scale=1.0">

    <link type="text/css" rel="stylesheet" href="//fonts.googleapis.com/css?family=Source+Sans+Pro:400,400italic,700,700italic" />
    <link rel="stylesheet" type="text/css" href="/css/styles.css" />

</head>

<body>
    <header>
        <h1><a href="/">Pop PHP Framework Skeleton Application</a></h1>
    </header>
<!-- Content //-->
    <div id="content">
        <h1 style="color: #f00;"><?=$title; ?></h1>
        <p>
            Sorry, that page was not found.
        </p>
    </div>
<!-- Footer //-->
    <footer>
        <a href="http://www.popphp.org/" target="_blank">Pop PHP Framework</a> on <a href="https://github.com/popphp/" target="_blank">Github</a>.
    </footer>
</body>

</html>
