<!DOCTYPE html>
<!-- Header //-->
<html>

<head>

    <title>
        <?=$title; ?> : Pop PHP Framework Skeleton Application
    </title>

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="initial-scale=1.0">

    <link type="text/css" rel="stylesheet" href="//fonts.googleapis.com/css?family=Source+Sans+Pro:400,400italic,700,700italic" />
    <link rel="stylesheet" type="text/css" href="/css/styles.css" />

</head>

<body>
    <header>
        <h1><a href="/">Pop PHP Framework Skeleton Application</a></h1>
    </header>
<!-- Content //-->
    <div id="content">
        <h1><?=$title; ?>, <?=$name;?></h1>
        <p>
            And welcome to Pop!
        </p>
        <div><input type="text" id="name" name="name" value="" size="25" placeholder="Enter your name..." /></div>
        <div><input type="submit" name="submit" id="hello" value="Say Hello!" /></div>
    </div>
<!-- Footer //-->
    <footer>
        <a href="http://www.popphp.org/" target="_blank">Pop PHP Framework</a> on <a href="https://github.com/popphp/" target="_blank">Github</a>.
    </footer>
</body>
<script type="text/javascript">
    document.getElementById('hello').onclick = function(e){
        window.location = '/hello/' + document.getElementById('name').value;
    };
</script>
</html>
