<!DOCTYPE html>
<!-- Header //-->
<html>

<head>

    <title>
        <?=$title; ?> : Pop PHP Framework Skeleton Application
    </title>

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="initial-scale=1.0">

    <link type="text/css" rel="stylesheet" href="//fonts.googleapis.com/css?family=Source+Sans+Pro:400,400italic,700,700italic" />
    <link rel="stylesheet" type="text/css" href="/css/styles.css" />

</head>

<body>
    <header>
        <h1><a href="/">Pop PHP Framework Skeleton Application</a></h1>
    </header>
<!-- Content //-->
    <div id="content">
        <h1><?=$title; ?></h1>
        <p>
            Thank you for your interest in the Pop PHP Framework. The Pop PHP Framework is a lightweight,
            yet robust PHP framework that can be used for rapid application development. The framework
            itself has a base set of core components as well as numerous other additional components to
            facilitate many of the common features needed for a PHP application.
        </p>
        <p>
            This skeleton application is designed to give some insight into the structure and layout of
            a simple application layout.
        </p>
    </div>
<!-- Footer //-->
    <footer>
        <a href="http://www.popphp.org/" target="_blank">Pop PHP Framework</a> on <a href="https://github.com/popphp/" target="_blank">Github</a>.
    </footer>
</body>

</html>
